version: "3"

services:
  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tests
    ports:
      - "5436:5432"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9005:80"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"